"use client";

import Link from "next/link";
import { useAuth } from "../../providers";

const ACCESOS = [
  { href: "/cartera", titulo: "Mi cartera", texto: "Acompaña cada oportunidad", color: "bg-[#eaf4fb]", icono: "♡" },
  { href: "/anuncios", titulo: "Propiedades", texto: "Comparte opciones con confianza", color: "bg-[#fff0bf]", icono: "⌂" },
  { href: "/foro", titulo: "Foro del equipo", texto: "Preguntamos, aprendemos y crecemos", color: "bg-[#e9f4e7]", icono: "✦" },
  { href: "/calendario", titulo: "Agenda", texto: "Coordinamos cada paso", color: "bg-[#f6f2ec]", icono: "◷" },
];
const FRASES = ["La confianza abre puertas.", "Juntos hacemos que suceda.", "Cada familia merece sentirse acompañada."];
export default function InicioPage() { const { profile } = useAuth(); const nombre = profile?.nombre?.split(" ")[0] || "equipo"; return <div className="space-y-6"><section className="relative min-h-[340px] overflow-hidden rounded-[2rem] bg-[#102b4e] bg-cover bg-center shadow-xl" style={{ backgroundImage: "linear-gradient(90deg, rgba(16,43,78,.98) 0%, rgba(16,43,78,.84) 34%, rgba(16,43,78,.2) 82%), url('/hinova-family.jpg')" }}><div className="relative z-[1] max-w-2xl p-6 text-white sm:p-9"><p className="text-sm font-semibold uppercase tracking-[.18em] text-[#b9d9ee]">Bienvenida, {nombre}</p><h1 className="mt-4 text-3xl font-bold leading-tight sm:text-5xl">Crecemos juntos, acompañamos sueños.</h1><p className="mt-5 max-w-xl text-base leading-7 text-[#d7e6f1]">Tu espacio HINOVA para trabajar con orden, cuidar cada relación y avanzar con el respaldo de todo el equipo.</p><div className="mt-7 flex flex-wrap gap-2"><span className="rounded-full bg-white/15 px-3 py-2 text-sm text-white">Confianza</span><span className="rounded-full bg-white/15 px-3 py-2 text-sm text-white">Servicio</span><span className="rounded-full bg-white/15 px-3 py-2 text-sm text-white">Trabajo en equipo</span></div></div></section><section className="grid gap-3 sm:grid-cols-3">{FRASES.map((frase, i) => <div key={frase} className="card bg-white/80"><span className="text-xl text-[#e09f18]">{i === 0 ? "✦" : i === 1 ? "♡" : "⌂"}</span><p className="mt-2 font-semibold leading-6 text-[#102b4e]">{frase}</p><p className="mt-1 text-xs text-[#718094]">HINOVA Inmobiliaria</p></div>)}</section><section><div className="mb-3"><p className="text-sm font-semibold uppercase tracking-wide text-[#718094]">Tu espacio de hoy</p><h2 className="text-2xl font-bold text-[#102b4e]">¿Qué necesitas hacer?</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{ACCESOS.map((item) => <Link key={item.href} href={item.href} className={`${item.color} group rounded-3xl p-5 transition hover:-translate-y-1 hover:shadow-lg`}><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white/80 text-xl text-[#102b4e]">{item.icono}</span><h3 className="mt-5 text-lg font-bold text-[#102b4e]">{item.titulo}</h3><p className="mt-1 text-sm leading-5 text-[#526171]">{item.texto}</p><span className="mt-5 inline-block text-sm font-bold text-[#1f6aa5]">Abrir →</span></Link>)}</div></section><section className="card flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-[#e09f18]">Nuestro propósito</p><p className="mt-1 text-lg font-semibold text-[#102b4e]">“Cuando trabajamos unidos, cada cliente siente la diferencia.”</p></div><span className="text-3xl text-[#e09f18]" aria-hidden="true">✦</span></section></div>; }
