"use client";

import { estadoInfo } from "@/lib/estados";

function whatsappUrl(phone, message = "") { const raw = String(phone || "").replace(/[^\d+]/g, "").replace(/^\+/, ""); const number = raw.startsWith("0") ? `593${raw.slice(1)}` : raw; return `https://wa.me/${number}?text=${encodeURIComponent(message)}`; }

export default function ClienteCard({ cliente, onClick }) {
  const info = estadoInfo(cliente.estado); const hasPhone = String(cliente.telefono || "").replace(/\D/g, "").length >= 7;
  return <div className="card group w-full text-left transition hover:-translate-y-0.5 hover:shadow-lg"><div role="button" tabIndex={0} onClick={onClick} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") onClick(); }} className="cursor-pointer"><div className="flex items-start gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-[#eaf4fb] text-lg font-bold text-[#1f6aa5]">{`${cliente.nombres?.[0] || ""}${cliente.apellidos?.[0] || ""}`.toUpperCase()}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><span className="block text-base font-bold text-[#102b4e]">{cliente.nombres} {cliente.apellidos}</span><span className="mt-0.5 block text-sm text-[#718094]">{cliente.telefono || "Sin teléfono registrado"}</span></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${info.color}`}>{info.etiqueta}</span></div><div className="mt-3 flex flex-wrap gap-2 text-xs text-[#526171]">{cliente.busca_que && <span className="rounded-full bg-[#f6f2ec] px-2.5 py-1">Busca: {cliente.busca_que}</span>}{cliente.fecha_recontacto && <span className="rounded-full bg-[#fff0bf] px-2.5 py-1">Seguimiento: {cliente.fecha_recontacto}</span>}</div></div><span className="text-xl text-[#9eacb8] transition group-hover:translate-x-1">›</span></div></div><div className="mt-4 flex gap-2 border-t border-[#eee9e2] pt-3"><a className={`rounded-xl px-3 py-2 text-xs font-bold ${hasPhone ? "bg-[#e9f4e7] text-[#38734a] hover:bg-[#d9ecd9]" : "cursor-not-allowed bg-[#f3f0eb] text-[#9aa3ad]"}`} href={hasPhone ? whatsappUrl(cliente.telefono, `Hola ${cliente.nombres}, te saluda tu asesora de HINOVA.`) : undefined} target="_blank" rel="noreferrer" onClick={(event) => { if (!hasPhone) event.preventDefault(); }}>WhatsApp</a><span className="py-2 text-xs text-[#9aa3ad]">Abrir ficha para editar</span></div></div>;
}
