"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabaseClient";
import { useAuth } from "../../providers";
import { ESTADOS } from "@/lib/estados";
import ClienteCard from "@/components/ClienteCard";
import ClienteForm from "@/components/ClienteForm";

export default function CarteraPage() {
  const { profile } = useAuth();
  const [clientes, setClientes] = useState([]); const [tab, setTab] = useState("nuevo"); const [busqueda, setBusqueda] = useState(""); const [editando, setEditando] = useState(null); const [creando, setCreando] = useState(false); const [guardando, setGuardando] = useState(false); const [error, setError] = useState("");
  async function cargar() { if (!profile) return; const { data, error } = await supabase.from("clientes").select("*").eq("asesora_id", profile.id).eq("archivado", false).order("created_at", { ascending: false }); if (error) setError("No pudimos cargar tu cartera. Intenta actualizar la página."); setClientes(data || []); }
  useEffect(() => { cargar(); }, [profile]);
  function limpiarPayload(form) { return { ...form, asesora_id: profile.id, num_hijos: form.num_hijos === "" || form.num_hijos == null ? 0 : Number(form.num_hijos), num_carros: form.num_carros === "" || form.num_carros == null ? 0 : Number(form.num_carros), presupuesto: form.presupuesto === "" || form.presupuesto == null ? null : Number(form.presupuesto), monto_credito: form.monto_credito === "" || form.monto_credito == null ? null : Number(form.monto_credito), fecha_recontacto: form.fecha_recontacto === "" ? null : form.fecha_recontacto }; }
  async function guardar(form) { setGuardando(true); const payload = limpiarPayload(form); const result = editando?.id ? await supabase.from("clientes").update(payload).eq("id", editando.id) : await supabase.from("clientes").insert(payload); setGuardando(false); if (result.error) { alert("No se pudo guardar: " + result.error.message); return; } setEditando(null); setCreando(false); cargar(); }
  const visibles = clientes.filter((c) => busqueda ? `${c.nombres} ${c.apellidos}`.toLowerCase().includes(busqueda.toLowerCase()) : c.estado === tab);
  if (creando || editando) return <ClienteForm inicial={editando} onGuardar={guardar} onCancelar={() => { setEditando(null); setCreando(false); }} guardando={guardando} />;
  return <div className="space-y-5"><section className="flex flex-col gap-4 rounded-3xl bg-[#eaf4fb] p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-wide text-[#1f6aa5]">Tu seguimiento</p><h1 className="mt-1 text-2xl font-bold text-[#102b4e]">Mi cartera</h1><p className="mt-1 text-sm text-[#526171]">Cada relación cuenta. Registra el próximo paso.</p></div><button className="btn-primary" onClick={() => setCreando(true)}>+ Agregar cliente</button></section><div className="relative"><span className="pointer-events-none absolute left-3 top-3 text-[#718094]">⌕</span><input className="input pl-9" placeholder="Buscar por nombre…" value={busqueda} onChange={(e) => setBusqueda(e.target.value)} /></div>{error && <p className="rounded-2xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}{!busqueda && <div className="flex gap-2 overflow-x-auto pb-1">{ESTADOS.map((e) => <button key={e.valor} onClick={() => setTab(e.valor)} className={`tab ${tab === e.valor ? "tab-active" : "tab-inactive"}`}>{e.etiqueta}<span className="ml-1 opacity-70">{clientes.filter((c) => c.estado === e.valor).length}</span></button>)}</div>}<div className="space-y-3">{visibles.length === 0 && <div className="card py-10 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[#fff0bf] text-2xl">♡</div><h2 className="mt-4 font-bold text-[#102b4e]">Aún no hay clientes en esta etapa</h2><p className="mx-auto mt-1 max-w-sm text-sm text-[#718094]">Agrega tu primer contacto y acompáñalo paso a paso.</p><button className="btn-primary mt-5" onClick={() => setCreando(true)}>Agregar primer cliente</button></div>}{visibles.map((c) => <ClienteCard key={c.id} cliente={c} onClick={() => setEditando(c)} />)}</div></div>;
}
